### ISSUE TITLE
Part-size BS-X games might not have their checksum calculated correctly

### ISSUE THREAD

**Issue by redeemer665** [mrehkopf/sd2snes#28]
When checking and calculating the checksum of BS-X software upon booting it should be done only on the data banks indicated by the size byte at 0x7FD0 (or 0xFFD0), instead of simply summing all bytes in the ROM image. This is especially crucial with 8M cartridge images which have more than one program.

However there might be something else as well as I did a quick test with "BS Satesupo  DX Dai-4-Gou" (MD5: 442384ED70AF69F594C8CEC93E6DE81E) which has a size byte of 07h meaning the data is in the first three banks (3 Mb). Checksum is correct but it won't boot on sd2snes, it isn't giving me "Error 09" though.

When I change the internal size (0x7FD0) to FFh, ROM type byte (0x7FD9) to Full size (10h) and calculate a new checksum (5AD2, inverse A52D) everything works perfectly.

**Comment by mrehkopf** [comment]
The standalone 3ji no Wide Shou dump is an interesting case - it has a seemingly invalid header (vector table is filled with 0xffff) but the BSX BIOS knows how to run it anyway. sd2snes currently doesn't detect a valid header (every possible header locations gets a score of 0 due to the invalid vector table) and runs it as fallback (plain LoROM, no BSX). Needless to say that doesn't work either. ;) I tweaked header detection a bit to allow for detection, hopefully with no impact on other (mostly PD) ROM detection.

@LuigiBlood - have you seen something like it? How does the BSX BIOS know how to run such a game?

**Comment by LuigiBlood** [comment]
It's a ROM that runs on BS-X's script system.
The header has the info, after "01", you see 0x00000100 (in little endian). That's what tells the BS-X it is a script-based software.
